/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myjnidemo_LameUtils */

#ifndef _Included_com_example_myjnidemo_LameUtils
#define _Included_com_example_myjnidemo_LameUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myjnidemo_LameUtils
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_myjnidemo_LameUtils_convertmp3
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_myjnidemo_LameUtils
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myjnidemo_LameUtils_getLameVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
